export const FEATURE_FLAGS = {
  ENABLE_EMBEDDING_CHECKS: 'ENABLE_EMBEDDING_CHECKS',
  ENABLE_LLM_CHECKS: 'ENABLE_LLM_CHECKS',
  ENABLE_CIRCUIT_BREAKERS: 'ENABLE_CIRCUIT_BREAKERS',
  ENABLE_DASHBOARD_WEBSOCKETS: 'ENABLE_DASHBOARD_WEBSOCKETS',
  ENABLE_PARTITIONED_LOGGING: 'ENABLE_PARTITIONED_LOGGING'
};