import { EventEmitter } from 'events';

/**
 * Represents the possible states of a token in the document
 */
export enum TokenState {
  DEFAULT = 'default',     // Normal state
  ACCEPTED = 'accepted',   // Explicitly accepted by user
  REJECTED = 'rejected',   // Explicitly rejected by user
  CONFLICT = 'conflict',   // In conflict with another edit
  PENDING = 'pending',     // Waiting for user decision
  AI_GENERATED = 'ai'      // Generated by AI
}

/**
 * Represents metadata for a token in the document
 */
export interface TokenMetadata {
  state: TokenState;
  userId?: string;         // ID of user who created/modified the token
  timestamp?: number;      // When the token was created/modified
  sourceId?: string;       // Source of the token (e.g., AI command ID)
  conflictIds?: string[];  // IDs of conflicting operations
  confidence?: number;     // AI confidence score (0-1)
}

/**
 * Interface for a token in the document
 */
export interface Token {
  id: string;              // Unique ID for the token
  text: string;            // The actual text content
  position: number;        // Position in the document
  length: number;          // Length of the token
  metadata: TokenMetadata; // State and other metadata
}

/**
 * Options for the TokenStateManager
 */
export interface TokenStateManagerOptions {
  documentId: string;
  userId: string;
  tenantId: string;
  initialTokens?: Token[];
}

/**
 * Manages the state of tokens in a document, including conflict resolution
 */
export class TokenStateManager extends EventEmitter {
  private documentId: string;
  private userId: string;
  private tenantId: string;
  private tokens: Map<string, Token> = new Map();
  private positionIndex: Map<number, string[]> = new Map();
  
  /**
   * Creates a new TokenStateManager
   */
  constructor(options: TokenStateManagerOptions) {
    super();
    this.documentId = options.documentId;
    this.userId = options.userId;
    this.tenantId = options.tenantId;
    
    // Initialize with any provided tokens
    if (options.initialTokens) {
      this.initializeTokens(options.initialTokens);
    }
  }
  
  /**
   * Initialize the manager with a set of tokens
   */
  private initializeTokens(tokens: Token[]): void {
    tokens.forEach(token => {
      this.tokens.set(token.id, token);
      this.indexTokenPosition(token);
    });
  }
  
  /**
   * Index a token by its position for quick lookup
   */
  private indexTokenPosition(token: Token): void {
    const position = token.position;
    if (!this.positionIndex.has(position)) {
      this.positionIndex.set(position, []);
    }
    this.positionIndex.get(position)?.push(token.id);
  }
  
  /**
   * Add a new token to the document
   */
  addToken(token: Token): void {
    // Ensure the token has valid metadata
    if (!token.metadata) {
      token.metadata = { state: TokenState.DEFAULT };
    }
    
    // Check for conflicts at this position
    const existingTokenIds = this.getTokensAtPosition(token.position);
    let hasConflict = false;
    
    if (existingTokenIds.length > 0) {
      // Record conflicts and update state
      token.metadata.state = TokenState.CONFLICT;
      token.metadata.conflictIds = existingTokenIds;
      hasConflict = true;
      
      // Update existing tokens to mark the conflict
      existingTokenIds.forEach(id => {
        const existingToken = this.tokens.get(id);
        if (existingToken) {
          existingToken.metadata.state = TokenState.CONFLICT;
          if (!existingToken.metadata.conflictIds) {
            existingToken.metadata.conflictIds = [];
          }
          existingToken.metadata.conflictIds.push(token.id);
          this.tokens.set(id, existingToken);
        }
      });
    }
    
    // Add the token
    this.tokens.set(token.id, token);
    this.indexTokenPosition(token);
    
    // Emit events
    this.emit('tokenAdded', token);
    if (hasConflict) {
      this.emit('conflictDetected', {
        newToken: token,
        existingTokenIds
      });
    }
  }
  
  /**
   * Update the state of a token
   */
  updateTokenState(tokenId: string, newState: TokenState): void {
    const token = this.tokens.get(tokenId);
    if (!token) {
      throw new Error(`Token with ID ${tokenId} not found`);
    }
    
    const oldState = token.metadata.state;
    token.metadata.state = newState;
    
    // Handle state transition side effects
    if (newState === TokenState.ACCEPTED) {
      this.handleTokenAccepted(token);
    } else if (newState === TokenState.REJECTED) {
      this.handleTokenRejected(token);
    }
    
    this.tokens.set(tokenId, token);
    this.emit('tokenStateChanged', {
      tokenId,
      oldState,
      newState
    });
  }
  
  /**
   * Handle side effects when a token is accepted
   */
  private handleTokenAccepted(token: Token): void {
    // If this token was in conflict, resolve the conflict by rejecting conflicting tokens
    if (token.metadata.conflictIds?.length) {
      token.metadata.conflictIds.forEach(conflictId => {
        const conflictingToken = this.tokens.get(conflictId);
        if (conflictingToken && conflictingToken.metadata.state === TokenState.CONFLICT) {
          conflictingToken.metadata.state = TokenState.REJECTED;
          this.tokens.set(conflictId, conflictingToken);
          this.emit('tokenStateChanged', {
            tokenId: conflictId,
            oldState: TokenState.CONFLICT,
            newState: TokenState.REJECTED
          });
        }
      });
      
      // Clear the conflict IDs since the conflict is resolved
      token.metadata.conflictIds = [];
    }
  }
  
  /**
   * Handle side effects when a token is rejected
   */
  private handleTokenRejected(token: Token): void {
    // If this token was in conflict, resolve the conflict by accepting the other tokens
    if (token.metadata.conflictIds?.length) {
      token.metadata.conflictIds.forEach(conflictId => {
        const conflictingToken = this.tokens.get(conflictId);
        if (conflictingToken && conflictingToken.metadata.state === TokenState.CONFLICT) {
          conflictingToken.metadata.state = TokenState.ACCEPTED;
          this.tokens.set(conflictId, conflictingToken);
          this.emit('tokenStateChanged', {
            tokenId: conflictId,
            oldState: TokenState.CONFLICT,
            newState: TokenState.ACCEPTED
          });
        }
      });
      
      // Clear the conflict IDs since the conflict is resolved
      token.metadata.conflictIds = [];
    }
  }
  
  /**
   * Get all tokens at a specific position
   */
  getTokensAtPosition(position: number): string[] {
    return this.positionIndex.get(position) || [];
  }
  
  /**
   * Get a token by its ID
   */
  getToken(tokenId: string): Token | undefined {
    return this.tokens.get(tokenId);
  }
  
  /**
   * Get all tokens in the document
   */
  getAllTokens(): Token[] {
    return Array.from(this.tokens.values());
  }
  
  /**
   * Get tokens in a specific state
   */
  getTokensByState(state: TokenState): Token[] {
    return Array.from(this.tokens.values())
      .filter(token => token.metadata.state === state);
  }
  
  /**
   * Get tokens with conflicts
   */
  getConflictingTokens(): Token[] {
    return Array.from(this.tokens.values())
      .filter(token => token.metadata.state === TokenState.CONFLICT);
  }
  
  /**
   * Check if there are any unresolved conflicts
   */
  hasUnresolvedConflicts(): boolean {
    return this.getConflictingTokens().length > 0;
  }
  
  /**
   * Resolve all conflicts using a specific strategy
   */
  resolveAllConflicts(strategy: 'accept-newest' | 'accept-oldest' | 'accept-local' | 'accept-remote'): void {
    const conflictingTokens = this.getConflictingTokens();
    
    for (const token of conflictingTokens) {
      if (!token.metadata.conflictIds?.length) continue;
      
      // Get all tokens involved in this conflict
      const tokensInConflict = [token, ...token.metadata.conflictIds.map(id => this.tokens.get(id)).filter(Boolean) as Token[]];
      
      // Determine which token to accept based on strategy
      let tokenToAccept: Token | undefined;
      
      switch (strategy) {
        case 'accept-newest':
          tokenToAccept = tokensInConflict.reduce((newest, current) => 
            (current.metadata.timestamp || 0) > (newest.metadata.timestamp || 0) ? current : newest
          , tokensInConflict[0]);
          break;
          
        case 'accept-oldest':
          tokenToAccept = tokensInConflict.reduce((oldest, current) => 
            (current.metadata.timestamp || 0) < (oldest.metadata.timestamp || 0) ? current : oldest
          , tokensInConflict[0]);
          break;
          
        case 'accept-local':
          tokenToAccept = tokensInConflict.find(t => t.metadata.userId === this.userId);
          break;
          
        case 'accept-remote':
          tokenToAccept = tokensInConflict.find(t => t.metadata.userId !== this.userId);
          break;
      }
      
      // Accept the selected token and reject others
      if (tokenToAccept) {
        this.updateTokenState(tokenToAccept.id, TokenState.ACCEPTED);
      }
    }
  }
  
  /**
   * Convert the token state into a style object for rendering
   */
  getTokenStyle(tokenId: string): Record<string, string> {
    const token = this.tokens.get(tokenId);
    if (!token) return {};
    
    switch (token.metadata.state) {
      case TokenState.ACCEPTED:
        return { backgroundColor: 'rgba(0, 255, 0, 0.2)', color: 'inherit' };
      case TokenState.REJECTED:
        return { backgroundColor: 'rgba(255, 0, 0, 0.2)', textDecoration: 'line-through', color: 'gray' };
      case TokenState.CONFLICT:
        return { backgroundColor: 'rgba(255, 255, 0, 0.2)', outline: '1px dashed orange' };
      case TokenState.PENDING:
        return { backgroundColor: 'rgba(0, 0, 255, 0.1)', fontStyle: 'italic' };
      case TokenState.AI_GENERATED:
        return { backgroundColor: 'rgba(128, 0, 128, 0.1)', color: 'purple' };
      default:
        return {};
    }
  }
  
  /**
   * Export the current token state for persistence
   */
  exportState(): { tokens: Token[] } {
    return {
      tokens: Array.from(this.tokens.values())
    };
  }
  
  /**
   * Import token state from persistence
   */
  importState(state: { tokens: Token[] }): void {
    this.tokens.clear();
    this.positionIndex.clear();
    this.initializeTokens(state.tokens);
    this.emit('stateImported', state);
  }
}