import { CommandEventIntegrator } from '../../../src/collaboration/integration/CommandEventIntegrator';
import { TransactionManager } from '../../../src/collaboration/transactions/TransactionManager';
import { EventStore } from '../../../src/collaboration/events/EventStore';
import { MetricsCollector } from '../../../src/metrics/metrics-collector';
import { Command } from '../../../src/collaboration/commands/CommandRegistry';

jest.mock('../../../src/metrics/collector');
jest.mock('../../../src/collaboration/events/EventStore');
jest.mock('../../../src/collaboration/transactions/TransactionManager');
jest.mock('../../../src/lib/tenant-context', () => ({
  getTenantContext: jest.fn().mockReturnValue({
    tenantId: 'test-tenant',
    userId: 'test-user'
  })
}));

describe('CommandEventIntegrator', () => {
  let commandEventIntegrator: CommandEventIntegrator;
  let eventStore: jest.Mocked<EventStore>;
  let transactionManager: jest.Mocked<TransactionManager>;
  let metricsCollector: jest.Mocked<MetricsCollector>;
  
  beforeEach(() => {
    // Setup mocks
    eventStore = {
      store: jest.fn().mockResolvedValue({}),
    } as unknown as jest.Mocked<EventStore>;
    
    transactionManager = {
      executeInTransaction: jest.fn().mockImplementation(async (fn) => {
        const transaction = {
          id: 'mock-transaction',
          client: {},
          tenantId: 'test-tenant',
          timestamp: { wallTime: Date.now(), logical: 0, nodeId: 'test-node' }
        };
        return fn(transaction);
      }),
      getCurrentTimestamp: jest.fn().mockReturnValue({
        wallTime: Date.now(),
        logical: 0,
        nodeId: 'test-node'
      })
    } as unknown as jest.Mocked<TransactionManager>;
    
    metricsCollector = {
      recordLatency: jest.fn().mockResolvedValue(undefined),
      increment: jest.fn().mockResolvedValue(undefined),
      track: jest.fn().mockResolvedValue(undefined)
    } as unknown as jest.Mocked<MetricsCollector>;
    
    // Create CommandEventIntegrator
    commandEventIntegrator = new CommandEventIntegrator(
      eventStore, 
      transactionManager,
      metricsCollector
    );
  });
  
  test('should execute command and store events', async () => {
    // Sample command
    const command: Command = {
      type: 'INSERT_TEXT',
      payload: {
        documentId: 'doc-1',
        position: 0,
        text: 'Hello'
      }
    };
    
    // Sample events generated by the command
    const events = [
      {
        type: 'TEXT_INSERTED',
        documentId: 'doc-1',
        payload: {
          position: 0,
          text: 'Hello'
        },
        version: 1
      }
    ];
    
    // Command handler
    const handler = jest.fn().mockResolvedValue({
      result: { success: true },
      events
    });
    
    // Execute command
    const result = await commandEventIntegrator.executeCommand(command, handler);
    
    // Verify result
    expect(result).toEqual({ success: true });
    
    // Verify transaction was used
    expect(transactionManager.executeInTransaction).toHaveBeenCalled();
    
    // Verify handler was called with command
    expect(handler).toHaveBeenCalledWith(
      expect.objectContaining({
        type: 'INSERT_TEXT',
        tenantId: 'test-tenant',
        userId: 'test-user'
      }),
      expect.any(String) // transaction ID
    );
    
    // Verify events were stored
    expect(eventStore.store).toHaveBeenCalledWith(
      expect.objectContaining({
        type: 'TEXT_INSERTED',
        documentId: 'doc-1',
        payload: {
          position: 0,
          text: 'Hello'
        },
        metadata: expect.objectContaining({
          transactionId: expect.any(String),
          commandId: expect.any(String),
          timestamp: expect.any(Number),
          vectorClock: expect.any(Object)
        })
      }),
      expect.any(Object)
    );
    
    // Verify metrics were recorded
    expect(metricsCollector.recordLatency).toHaveBeenCalledWith(
      'command.INSERT_TEXT.execution',
      expect.any(Number)
    );
    expect(metricsCollector.increment).toHaveBeenCalledWith(
      'command.INSERT_TEXT.count',
      1
    );
  });
  
  test('should execute multiple commands in a single transaction', async () => {
    // Sample commands
    const commands: Command[] = [
      {
        type: 'INSERT_TEXT',
        payload: {
          documentId: 'doc-1',
          position: 0,
          text: 'Hello'
        }
      },
      {
        type: 'FORMAT_TEXT',
        payload: {
          documentId: 'doc-1',
          position: 0,
          length: 5,
          formatting: { bold: true }
        }
      }
    ];
    
    // Command handlers
    const handlers = [
      jest.fn().mockResolvedValue({
        result: { insertId: 1 },
        events: [{
          type: 'TEXT_INSERTED',
          documentId: 'doc-1',
          payload: { position: 0, text: 'Hello' },
          version: 1
        }]
      }),
      jest.fn().mockResolvedValue({
        result: { formatId: 1 },
        events: [{
          type: 'TEXT_FORMATTED',
          documentId: 'doc-1',
          payload: { position: 0, length: 5, formatting: { bold: true } },
          version: 2
        }]
      })
    ];
    
    // Execute commands
    const results = await commandEventIntegrator.executeCommands(commands, handlers);
    
    // Verify results
    expect(results).toEqual([{ insertId: 1 }, { formatId: 1 }]);
    
    // Verify single transaction was used
    expect(transactionManager.executeInTransaction).toHaveBeenCalledTimes(1);
    
    // Verify both handlers were called
    expect(handlers[0]).toHaveBeenCalled();
    expect(handlers[1]).toHaveBeenCalled();
    
    // Verify both events were stored
    expect(eventStore.store).toHaveBeenCalledTimes(2);
  });
  
  test('should handle errors and roll back transaction', async () => {
    // Sample command
    const command: Command = {
      type: 'INSERT_TEXT',
      payload: {
        documentId: 'doc-1',
        position: 0,
        text: 'Hello'
      }
    };
    
    // Mock transaction manager to simulate error
    transactionManager.executeInTransaction.mockImplementationOnce(() => {
      throw new Error('Test error');
    });
    
    // Command handler (should not be called due to transaction error)
    const handler = jest.fn();
    
    // Execute command should throw
    await expect(commandEventIntegrator.executeCommand(command, handler))
      .rejects.toThrow('Test error');
    
    // Verify error metrics were recorded
    expect(metricsCollector.increment).toHaveBeenCalledWith(
      'command.INSERT_TEXT.error',
      1
    );
    
    // Handler should not have been called
    expect(handler).not.toHaveBeenCalled();
  });
});